apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oil-pipeline.fullname" . }}-postgres-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oil-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- with .Values.postgres.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
